# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=1000)),
                ('data', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=1000)),
                ('data', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
