# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SICS', '0002_auto_20180415_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sender',
            new_name='sender_username',
        ),
        migrations.AddField(
            model_name='post',
            name='sender_first_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sender_last_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
