# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SICS', '0003_auto_20180415_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userA', models.CharField(max_length=30)),
                ('userB', models.CharField(max_length=30)),
            ],
        ),
    ]
